# Generated by Django 5.2.8 on 2025-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('murchison-falls', 'Murchison Falls National Park'), ('queen-elizabeth', 'Queen Elizabeth National Park'), ('lake-mburo', 'Lake Mburo National Park'), ('bwindi', 'Bwindi Impenetrable Forest')], max_length=50)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
